### ISSUE TITLE
MapNH Segmentation fault (core dumped) and Input Seq error!

### ISSUE THREAD

**Issue by Enhancer01** [BioPP/testnh#5]
I have been trying to use _MapNH_ in **TestNH**, version 3.0.0 but continue to face multiple challenges. I decided to run the examples in the example_folder and similar errors occurred, including Segmentation fault (core dumped) and input sequence error. A similar problem was observed with _BppML_ in **bppSuite** package as well.  I manage to run the BppML on my data after changing the sequence and tree "input names" to input.sequence.file and input.tree.file respectively. 

I have attached some of the errors generated while trying to run the examples provided with the library.
![LA_Mapnh](https://github.com/BioPP/testnh/assets/61864589/9685619c-2153-432b-b360-cbc27c91e350)
![Man_bppml](https://github.com/BioPP/testnh/assets/61864589/48551e28-7f3f-421d-b476-6dd9a729f9d3)
![Man_mapnh](https://github.com/BioPP/testnh/assets/61864589/42c1f046-2d27-466e-9edc-3ec9ac8ac226)
![LA_BppML](https://github.com/BioPP/testnh/assets/61864589/bfdb2918-dc24-4f7b-9faf-ba0b15621153)
![LA_BppML1](https://github.com/BioPP/testnh/assets/61864589/822fddac-068a-4671-84f6-4d3a3c334aad)

**Comment by lgueguen** [comment]
Hello,

you may have an issue with your update, since all examples compute well with the latest version.

Cheers,
Laurent

**Comment by Enhancer01** [comment]
Thank you @lgueguen . I have actually had challenges getting the latest version from github. I initially installed through BioConda, Bpp-seq, Bpp-core, Bpp-phyl, and Bpp-popgen. However, when I try to install TestNH, the attached _**image1**_ is what I get, and if I proceed to "make install", it generates several errors, _**image2.1 and 2.2**_. I use a server, but I don't have root privilege. I would appreciate you assistance in fixing this issue.
The older version (Static; 1.1.1) of MapNH that I got was from [here](https://github.com/BioPP/testnh/releases) 

Thank you. 
![Image1](https://github.com/BioPP/testnh/assets/61864589/ce5d06ac-e3dd-425a-b429-ea25927d0963)
![Image2 1](https://github.com/BioPP/testnh/assets/61864589/2b06a287-6a1b-44a1-b228-4a7f3a4e4428)
![Image2 2](https://github.com/BioPP/testnh/assets/61864589/7cc2ca28-9d7f-4f91-b95d-695cdf866778)

**Comment by jydu** [comment]
Hi,

We are not maintaining any Conda packages, so these are third-party images that are not necessarily up to date. If you are willing to use version 3.00 (which I guess you would like to), you should compile and install the latest version of the Bio++ libraries from GitHub. Once we have a final release of Bpp3, we will provide executables for bppSuite and testNH. Installing the libraries should be relatively straightforward, and we can provide assistance on Linux or MacOS.

Cheers,

Julien.

**Comment by Enhancer01** [comment]
Thank you @jydu for your response. Github was my first call for the compilation of Bio++ libraries. However, I kept running into errors with "_**make install**_". I was able to successfully install **_bpp-core_** but others(_**bpp- seqs/phyl/popgens**_) failed. Meanwhile, I removed all the conda versions before trying to install from github. I have attached copies of the error messages for your evaluation. I work with Bash/Linux server, I will greatly appreciate your guidance to successfully install these packages. 

![bpp -seq error](https://github.com/BioPP/testnh/assets/61864589/585f1277-e52d-4ead-8691-e2101bf1f189)
![bpp-phyl erro](https://github.com/BioPP/testnh/assets/61864589/37b0bed7-1c8a-4967-bc35-28800fbb2755)
![popgen_error](https://github.com/BioPP/testnh/assets/61864589/a61fa01c-226d-40ef-8384-0be1b059c94f)

**Comment by jydu** [comment]
Hi, 

there are some issues with your paths. First, make sure you have removed previously installed libs with Conda. Then, for each lib, do the following:

```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/software/BioPP -DBUILD_STATIC=ON ..
make install
```
Use the path you want, but it should be the same for all libs/programs, do not use a specific one for each library.
BUILD_STATIC is optional but a good idea, allowing you to build standalone executables.
It is also a good idea to make an external build (for instance in a subdirectory "build", this can prevent issues).

Hope this helps,

Julien.

**Comment by Enhancer01** [comment]
Thank you @jydu , I followed your instructions, using _**Build**_ and a _**fixed directory**_ for all the libs. The bpp-core was successfully installed but not the other libs (bpp-seq and bpp-phyl). The "make install" command usually fails as shown in the attached image file (_**Error1**_). I tried to install them in this order **bpp-core >>>bpp-seq>>>bpp-phyl**. No matter what I do, that's always the pattern of the error generated **_(error1_**). When I tried to install bpp-phyl without bpp-seq, it generated a Cmake error. 

I greatly appreciate your assistance in resolving this issue. 

![Error1](https://github.com/BioPP/testnh/assets/61864589/65c629d7-caf3-4687-92d7-241dfc553122)

**Comment by jydu** [comment]
Hi,

bpp-phyl requires bpp-seq, so we need to get the installation error of bpp-seq fixed first. I would need a bit more info:
- System you are using (Debian, Fedora, etc)
- The compiler (G++?) and its version
Also, could you attach the complete log of the cmake and make install commands for bpp-core and bpp-seq? (in text files, for instance doing `cmake .. >& cmake-bppcore.log` and `make install >& make-bppcore.log`)

Thanks for your perseverance,

Julien.

**Comment by Enhancer01** [comment]
Thank you @jydu, I so much appreciate all the efforts and time. 

1.  I am using Ubuntu 18.04.2 LTS (Desbian env); Kernel: Linux 5.4.0-72-generic. 

2. The compiler (G++?) and its version

         >gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

 I have attached all the logs for your evaluation.

[cmake-bppcore.txt](https://github.com/BioPP/testnh/files/12782057/cmake-bppcore.txt)
[cmake-bppseq.txt](https://github.com/BioPP/testnh/files/12782058/cmake-bppseq.txt)
[make-bppcore.txt](https://github.com/BioPP/testnh/files/12782059/make-bppcore.txt)
[make-bppseq.txt](https://github.com/BioPP/testnh/files/12782060/make-bppseq.txt)

**Comment by jydu** [comment]
Hum this is a tough one. I cannot reproduce the error but I tried sthg... can you update bpp-seq and try again? Please send again the complete make output if it still does not work.

Cheers,

Julien.

**Comment by Enhancer01** [comment]
Good evening @jydu , Thank you for all your effort and time. I updated bpp-seq and tried the installation but the behavior was exactly the same as the previous one.  I have uploaded the outputs for further evaluation.

[Cmake-bppseq.txt](https://github.com/BioPP/testnh/files/12830526/Cmake-bppseq.txt)
[Make-bppseq.txt](https://github.com/BioPP/testnh/files/12830528/Make-bppseq.txt)

**Comment by jydu** [comment]
Ok. It seems somehow that you do not have the latest version of the VectorTools.h file (from bpp-core).
Can you make sure that you do have installed the latest version of bpp-core (git pull and then make install)?
If you open the file /home/otunde/local/bpp/dev/include/Bpp/App/../Numeric/VectorTools.h, at line 529, the second argument of the function should be a vector<size_t>. If it is a vector<int>, then you do not have the latest version, and that is where the error comes from.

Julien.

**Comment by Enhancer01** [comment]
Good evening @jydu, I did a git pull in _**bpp-core**_ and it stated it's up-to-date. 
I opened the file  /home/otunde/local/bpp/dev/include/Bpp/App/../Numeric/VectorTools.h, at line 529, and this is what is there:          **_529_**     static std::vector<T> extract(const std::vector<T>& v1, const std::vector<int>& v2)

I thought you might want to take a look at the whole file, I have attached the VectorTools.h file for your evaluation

[VectorTools.h.txt](https://github.com/BioPP/testnh/files/12837232/VectorTools.h.txt)


Thank you for your time and effort.

**Comment by jydu** [comment]
Hi,

In the file you sent me, there is indeed
static std::vector<T> extract(const std::vector<T>& v1, const std::vector<int>& v2)
when it should be
static std::vector<T> extract(const std::vector<T>& v1, const std::vector<size_t>& v2)

So it is not the right version. We are getting there! In your bpp-core, can you check src/Bpp/Numeric/VectorTools.h? it should be with a size_t and not an int. If so, that means the installation of bpp-core failed, or it was installed somewhere else.

Checking at you make.log for bpp-core, I can see you are installing in /home/otunde/software/Bio++Library/BioPP
while here it is /home/otunde/local/bpp/dev/
So it seems you have two versions installed. You need to pass the exact same path to all libraries (CMAKE_INSTALL_PREFIX) for it to work. If you update and install all libs and progs in the same prefix, it should work!

Julien.

**Comment by Enhancer01** [comment]
Good evening @jydu, just as you stated, the src/Bpp/Numeric/VectorTools.h in bpp-core has vector<size_t>. I have removed all the bpp libs in conda env and have tried to delete all the bpp* directories to clone fresh libs from github.  

Today, I informed a colleague in the lab with root privilege about the challenges I've been facing and if he could install from his own end; he was able to install both the bpp-core and bpp-seq but not the bpp-phyl. I told him to follow the same instruction you gave me (same path for CMAKE_INSTALL_PREFIX). I have attached the error screen (_**cmake-bppphyl**_). 
Similarly, I got off the server to try and install the libs directly on my desktop through WSL/Ubuntu. Both the bpp-core and bpp-seq were successful but the bpp-phyl failed. I attached the log as a text file (_**cmake-bpp_phyl.txt**_). 

[cmake-bpp_phyl.txt](https://github.com/BioPP/testnh/files/12840428/cmake-bpp_phyl.txt)
![cmake-bppphyl](https://github.com/BioPP/testnh/assets/61864589/7bb33c6e-9214-4174-8e38-6a2d7b243810)

**Comment by Enhancer01** [comment]
Good evening @jydu, the bpp-seq has been installed successfully after removing this dir. /home/otunde/local/bpp/dev/. The bpp-core and bpp-seq have now been successful. However, the bpp-phyl failed. I have attached the error log, it's similar to what my colleague got as well. 

Thank you for all the effort and the time so far, I so much appreciate it. 

[cmake-bppPhyl.txt](https://github.com/BioPP/testnh/files/12844340/cmake-bppPhyl.txt)

**Comment by jydu** [comment]
This is a new error independent from the previous one... @lgueguen  I think you forgot to add some file in your last commit?

Julien.

**Comment by lgueguen** [comment]
Ouups,  sorry for this. 
I hope it is fixed now.

Laurent

**Comment by Enhancer01** [comment]
I am really grateful for all the time and effort. Thank you very much @jydu and @lgueguen, I was able to install all the dependencies. However, I still get _**make error**_ while trying to install _**testnh-3.0.0**_. I have attached the error.log for your evaluation.  
[cmake-testnh.txt](https://github.com/BioPP/testnh/files/12845952/cmake-testnh.txt)

**Comment by Enhancer01** [comment]
Meanwhile, when I git clone the [testnh](https://github.com/BioPP/testnh.git) and follow a similar installation procedure, the installation appears successful. However, if I type **_mapnh_** and **_ENTER_**, it produces an error. I have attached the error file for your evaluation. All three dependencies _**(bpp-core/bpp-seq/bpp-phyl**_) have been installed successfully.

 **_command_**: mapnh param=MapNH.bpp

_**Error**_: mapnh: Symbol `_ZTVN3bpp6NewickE' has different size in shared object, consider re-linking
mapnh: symbol lookup error: mapnh: undefined symbol: _ZNK3bpp22BppSequenceApplication21getConstAlignmentsMapERSt10shared_ptrIKNS_8AlphabetEEbbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESD_b

[mapnh.txt](https://github.com/BioPP/testnh/files/12864148/mapnh.txt)





On the other hand, if I **_wget_** [testnh-3.0.0](https://github.com/BioPP/testnh/archive/refs/tags/v3.0.0.tar.gz), the installation produces an error as I have reported two days ago in **_cmake-testnh.txt_**

I greatly appreciate all the support even as I complete the last leg of the installation process.

**Comment by jydu** [comment]
Hi,

the error you get with testnh can have several causes. If you linked dynamically, make sure that the LD_LIBRARY_PATH environment variable contains the path to the library that you installed, and not some other ones. If you installed in a path $PREFIX, then you should have
```
export LD_LIBRARY_PATH=$PREFIX/lib
```
It is easier if you compile testnh statically (cmake -DBUILD_STATIC=ON ..) for the libs and for testnh. Then the executable no longer need the libraries after being compiled.

Now, just in case, may I ask what you would like to use testnh for? The V3.00 currently only includes the mapnh program, the others have not yet been ported. So if that is what you need, then you're on the right tracks. But if you want to use some of the other programs like PartNH for instance, or if you do not need the latest developments of Bio++ V3, you may want to install the latest stable release (version 2.3.2, see https://github.com/BioPP/testnh/releases). Static executables are provided, which should work "out of the box" on a linux system.

Julien.

**Comment by Enhancer01** [comment]
@jydu, Thank you for all your efforts, it is now successful. My aim is to do something similar to this [paper](https://academic.oup.com/mbe/article/29/7/1861/1070227?login=false) where you described the software. I want to perform substitution mapping and cluster similar branches together.

**Comment by jydu** [comment]
Wow, that is PartNH. Then I strongly suggest that you use the last stable (static) version, even if it is a bit old. We have not ported PartNH to Bio++3.00 yet.

J.

**Comment by Enhancer01** [comment]
@jydu, I have done as you have suggested. I noticed a little disparity in the version, I downloaded _**testnh-x86_64-bin-static-2.3.2.tar.gz**_ but the **MapNH** and **PartNH** indicated _**version 1.1.1**_; I just want to know if it's okay that way. Also, are the syntax and parameters in the option_file similar across the versions? this stable static version does not have an option_file template. 

![TestNH-2 3 2](https://github.com/BioPP/testnh/assets/61864589/287e56a9-44e6-4f20-9c90-bdc7799295ac)

**Comment by jydu** [comment]
Hi,

The package number indicates which Bio++ version it uses. We should probably renumber the individual programs accordingly, as we did at some point for BppSuite. You can find the corresponding example files in the source package of the same version (also available in the Release section on GitHub).

J.

**Comment by Enhancer01** [comment]
@jydu,

I sincerely appreciate your effort and time that has enabled me to successfully set up this software.
I have some questions based on one of your papers (_**not software installation**_), kindly permit me to send you a direct email. 
 Thank you very much, I am very grateful. 

Sincerely,
Olatunde

**Comment by jydu** [comment]
Dear Olatunde,

Sure, feel free to do so (address is at the bottom of this page: https://molsysevol.github.io/index.html)

Julien.

**Comment by Enhancer01** [comment]
Thank you very much @jydu, I am sincerely grateful. 


Olatunde
